// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Chromapedia",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Chromapedia",
            targets: ["Chromapedia"],
            bundleIdentifier: "com.chromapedia.app",
            teamIdentifier: "RY74C6N3DD",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .camera(purposeString: "Chromapedia uses the camera to detect and identify colors in the real world.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "Chromapedia",
            path: "Sources",
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ]
        )
    ]
)